### ISSUE TITLE
2.1 Release Checklist

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#295]
- [x] Close any final blocking issues
- [x] Manual regression testing
  - Test on UEFI / BIOS
  - Test Online / Offline install
  - Run @spartan782's new test suite against successful installs
- [x] Copy needed RPMs from COPR test repo to PackageCloud
- [x] Migrate each repo to master:
  - rock (followed by release RPM)
  - rock-dashboards
  - rock-scripts
  - rock-createiso
- [x] Add Elastic license info
- [x] Digitally sign ISO and all the things
...
Profit!

---
EDIT: Added Elastic license task

**Comment by bndabbs** [comment]
Offline install against physical HW ✅ 
Online install in VirtualBox ✅ (After working around #292)

**Comment by dcode** [comment]
all done!
